#ifndef GLOBALHEAD
#define GLOBALHEAD
    #include <iostream>
    #include <string>
    #include <vector>
    #include <climits>
    #include <fstream>
    #include <cmath>
    #include <limits>
    #include <list>//STL list
    #include <map>// STL map
    #include <queue>// STL queue
    #include <stack>//sTL stack
    #include <bitset>//bitset可按位定义串
    #include <algorithm>//STL各种算法 比如 swap sort merge max min 比较
    #include <numeric>//常用数字操作 一般和algorithm搭配使用
    #include <functional>//STL定义运算函数（代替运算符）
    using namespace std;
#endif